sender2:sender2.c
	gcc sender2.c -o sender2
sender: sender.c
	gcc sender.c -o sender
receiver: receiver.c
	gcc receiver.c -o receiver
receiver2:
	gcc receiver2.c -o receiver2
sender3: sender3.c
	gcc sender3.c -o sender3
receiver3:receiver3.c
	gcc receiver3.c -o receiver3

all: sender sender2  receiver receiver2 sender3
