pthread_id:pthread_id.c
	gcc -pthread pthread_id.c -o pthread_id

pthread_exit:pthread_exit.c
	gcc -pthread pthread_exit.c -o pthread_exit

pthread_auto:pthread_auto.c
	gcc -pthread pthread_auto.c -o pthread_auto

pthread_atexit:pthread_atexit.c
	gcc -pthread pthread_atexit.c -o pthread_atexit

pthread_mutex:pthread_mutex.c
	gcc -pthread pthread_mutex.c -o pthread_mutex

pthread_mutex_try:pthread_mutex_try.c
	gcc -pthread pthread_mutex_try.c -o pthread_mutex_try

pthread_mutex_die:pthread_mutex_die.c
	gcc -pthread pthread_mutex_die.c -o pthread_mutex_die

pthread_mutex_die2:pthread_mutex_die2.c
	gcc -pthread pthread_mutex_die2.c -o pthread_mutex_die2

pthread_rwlock:pthread_rwlock.c
	gcc -pthread pthread_rwlock.c -o pthread_rwlock

pthread_rwlock2:pthread_rwlock2.c
	gcc -pthread pthread_rwlock2.c -o pthread_rwlock2

pthread_rwlock3:pthread_rwlock3.c
	gcc -pthread pthread_rwlock3.c -o pthread_rwlock3

pthread_rwlock4:pthread_rwlock4.c
	gcc -pthread pthread_rwlock4.c -o pthread_rwlock4

pthread_cond:pthread_cond.c
	gcc -pthread pthread_cond.c -o pthread_cond

.PHONY:clean
clean:
	rm pthread_id pthread_exit pthread_auto pthread_atexit pthread_mutex pthread_mutex_try pthread_mutex_die pthread_mutex_die2 pthread_rwlock pthread_rwlock1 pthread_rwlock2 pthread_rwlock3 pthread_rwlock4 pthread_cond

